development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: affiliate-notification_production

test:
  adapter: async

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: affiliate-notification_production
